version: "2"
services:
  bitwardenrs:
    image: vaultwarden/server:latest
    container_name: bitwardenrs
    volumes:
      - <Your data storage path here>:/data/
    ports:
      - <your port here>:80
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
      ADMIN_TOKEN: <your admin token here>
      
